package ast

import (
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
)

// PythonSourceRoots returns the set of directory prefixes (relative to
// projectRoot, slash-form) that should be prepended to a Python import
// path to match a pincher symbol QN.
//
// Returned in priority order:
//   - declared source dirs from pyproject.toml / setup.py / setup.cfg first
//   - implicit roots discovered by walking for __init__.py
//   - "" always last (identity / flat layout)
//
// All entries are non-trailing-slash, slash-separated. Convert with
// strings.ReplaceAll(root, "/", ".") to get the dotted prefix.
//
// Example: a project with `src/zelosmcp/__init__.py` returns
// `["src", ""]`. A flat layout `myproj/__init__.py` returns `[""]`.
func PythonSourceRoots(projectRoot string) []string {
	roots := map[string]struct{}{}

	for _, r := range pythonRootsFromPyproject(projectRoot) {
		roots[normalizeRoot(r)] = struct{}{}
	}
	for _, r := range pythonRootsFromSetupPy(projectRoot) {
		roots[normalizeRoot(r)] = struct{}{}
	}
	for _, r := range pythonRootsFromSetupCfg(projectRoot) {
		roots[normalizeRoot(r)] = struct{}{}
	}
	for _, r := range pythonRootsFromInitWalk(projectRoot) {
		roots[normalizeRoot(r)] = struct{}{}
	}
	// Identity is always a fallback — covers cases where the user wrote
	// the absolute path in the import (rare) or where detection missed.
	roots[""] = struct{}{}

	out := make([]string, 0, len(roots))
	for r := range roots {
		out = append(out, r)
	}
	// Longest first so the most specific prefix wins when a project has
	// both a src layout and stray top-level packages — the resolver tries
	// candidates in order and accepts the first hit, which makes
	// re-resolution deterministic.
	sort.SliceStable(out, func(i, j int) bool {
		if len(out[i]) != len(out[j]) {
			return len(out[i]) > len(out[j])
		}
		return out[i] < out[j]
	})
	return out
}

func normalizeRoot(r string) string {
	r = strings.TrimSpace(r)
	r = strings.Trim(r, "/\\")
	r = filepath.ToSlash(r)
	if r == "." {
		return ""
	}
	return r
}

// pyprojectTOML mirrors only the sub-tables PythonSourceRoots cares about,
// each lifted out as a free-form map so missing/divergent keys don't fail
// the whole decode. The TOML library tolerates extra fields silently.
type pyprojectTOML struct {
	Tool map[string]toml.Primitive `toml:"tool"`
}

func pythonRootsFromPyproject(projectRoot string) []string {
	path := filepath.Join(projectRoot, "pyproject.toml")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var meta toml.MetaData
	var doc pyprojectTOML
	if meta, err = toml.Decode(string(data), &doc); err != nil {
		return nil
	}

	roots := []string{}

	// setuptools: [tool.setuptools].package-dir = {"" = "src"} and
	// [tool.setuptools.packages.find].where = ["src"].
	if raw, ok := doc.Tool["setuptools"]; ok {
		var st struct {
			PackageDir map[string]string `toml:"package-dir"`
			Packages   struct {
				Find struct {
					Where []string `toml:"where"`
				} `toml:"find"`
			} `toml:"packages"`
		}
		if err := meta.PrimitiveDecode(raw, &st); err == nil {
			for _, v := range st.PackageDir {
				roots = append(roots, v)
			}
			roots = append(roots, st.Packages.Find.Where...)
		}
	}

	// poetry: [tool.poetry].packages = [{include = "x", from = "src"}].
	if raw, ok := doc.Tool["poetry"]; ok {
		var po struct {
			Packages []struct {
				Include string `toml:"include"`
				From    string `toml:"from"`
			} `toml:"packages"`
		}
		if err := meta.PrimitiveDecode(raw, &po); err == nil {
			for _, p := range po.Packages {
				if p.From != "" {
					roots = append(roots, p.From)
				}
			}
		}
	}

	// hatch: [tool.hatch.build.targets.wheel].packages = ["src/x"].
	if raw, ok := doc.Tool["hatch"]; ok {
		var ha struct {
			Build struct {
				Targets struct {
					Wheel struct {
						Packages []string `toml:"packages"`
					} `toml:"wheel"`
				} `toml:"targets"`
			} `toml:"build"`
		}
		if err := meta.PrimitiveDecode(raw, &ha); err == nil {
			for _, p := range ha.Build.Targets.Wheel.Packages {
				// "src/foo" → root "src". "foo" → root "".
				if i := strings.LastIndex(p, "/"); i >= 0 {
					roots = append(roots, p[:i])
				}
			}
		}
	}

	return roots
}

// setup.py is Python code, not declarative — full parsing is out of scope.
// We accept the common-case patterns generated by cookiecutters and most
// hand-written setup.py files. Missed exotic patterns just fall back to
// __init__.py walking, which catches them anyway.

var (
	rePackageDir = regexp.MustCompile(`package_dir\s*=\s*\{[^}]*['"]\s*['"]\s*:\s*['"]([^'"]+)['"]`)
	reFindWhere  = regexp.MustCompile(`find_packages\s*\(\s*(?:where\s*=\s*)?['"]([^'"]+)['"]`)
)

func pythonRootsFromSetupPy(projectRoot string) []string {
	data, err := os.ReadFile(filepath.Join(projectRoot, "setup.py"))
	if err != nil {
		return nil
	}
	src := string(data)
	roots := []string{}
	if m := rePackageDir.FindStringSubmatch(src); m != nil {
		roots = append(roots, m[1])
	}
	if m := reFindWhere.FindStringSubmatch(src); m != nil {
		roots = append(roots, m[1])
	}
	return roots
}

var (
	reCfgPackageDir = regexp.MustCompile(`(?m)^\s*package_dir\s*=\s*\n\s*=\s*([^\s]+)\s*$`)
	reCfgWhere      = regexp.MustCompile(`(?m)^\s*where\s*=\s*([^\s]+)\s*$`)
)

func pythonRootsFromSetupCfg(projectRoot string) []string {
	data, err := os.ReadFile(filepath.Join(projectRoot, "setup.cfg"))
	if err != nil {
		return nil
	}
	src := string(data)
	roots := []string{}
	if m := reCfgPackageDir.FindStringSubmatch(src); m != nil {
		roots = append(roots, m[1])
	}
	for _, m := range reCfgWhere.FindAllStringSubmatch(src, -1) {
		roots = append(roots, m[1])
	}
	return roots
}

// pythonRootsFromInitWalk derives source roots from __init__.py placement.
// For each top-most __init__.py in a chain, the directory CONTAINING that
// package (i.e. its parent) is a source root.
//
// Walk bounded by pythonRootsMaxDepth so a malformed monorepo can't make
// indexing pathologically slow. Skips the standard ignored dirs.
func pythonRootsFromInitWalk(projectRoot string) []string {
	const pythonRootsMaxDepth = 8

	// Set of relative paths of dirs containing __init__.py (slash form).
	pkgs := map[string]bool{}

	root := filepath.Clean(projectRoot)
	_ = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil // tolerate per-entry errors
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return nil
		}
		rel = filepath.ToSlash(rel)
		if d.IsDir() {
			if rel == "." {
				return nil
			}
			if pythonIsSkippedDir(d.Name()) {
				return filepath.SkipDir
			}
			if strings.Count(rel, "/") >= pythonRootsMaxDepth {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Name() == "__init__.py" {
			dir := strings.TrimSuffix(rel, "/__init__.py")
			if dir == "__init__.py" { // file lives at project root
				dir = ""
			}
			pkgs[dir] = true
		}
		return nil
	})

	roots := map[string]bool{}
	for pkg := range pkgs {
		// Walk up: the top-most __init__.py-bearing directory in this chain.
		top := pkg
		for {
			parent := parentDir(top)
			if parent == top || !pkgs[parent] {
				break
			}
			top = parent
		}
		roots[parentDir(top)] = true
	}

	out := make([]string, 0, len(roots))
	for r := range roots {
		out = append(out, r)
	}
	return out
}

func parentDir(p string) string {
	if p == "" || p == "." {
		return ""
	}
	i := strings.LastIndex(p, "/")
	if i < 0 {
		return ""
	}
	return p[:i]
}

func pythonIsSkippedDir(name string) bool {
	switch name {
	case ".git", "node_modules", "vendor", ".cache", "dist", "build",
		"__pycache__", ".venv", "venv", "env", "target", ".next", ".nuxt",
		"coverage", ".tox", ".pytest_cache", ".mypy_cache", ".ruff_cache",
		".eggs", ".idea", ".vscode":
		return true
	}
	return strings.HasPrefix(name, ".") && name != "."
}
